version: "3.8"

networks:
  proxy_bridge:
    external: true

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      proxy_bridge:
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.cryptoverse-secure.entrypoints: ${ENTRYPOINT}
      traefik.http.routers.cryptoverse-secure.rule: Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      traefik.http.services.cryptoverse-secure.loadbalancer.server.port: 80
      traefik.http.routers.cryptoverse-secure.middlewares: cryptoverse-redirect@file
      traefik.docker.network: proxy_bridge

  react:
    build:
      context: .
      dockerfile: dockerfiles/react.dockerfile
